### ISSUE TITLE
[BEESOFT-3.12.1] - MRJApp fails on OSX Sierra and JSE8

### ISSUE THREAD

**Issue by michaelDomingues** [beeverycreative/beethefirst-software#10]
![screen shot 2016-11-12 at 14 10 33](https://cloud.githubusercontent.com/assets/5079803/20238400/a651d686-a8e2-11e6-9593-8beb31f4febd.png)

BEESOFT hangs on initial startup thread and quits.
No entry added to **comLog** and **BEELOG**

**Comment by brunoaandrade** [comment]
Try to use the last version https://www.beeverycreative.com/public/software/BEESOFT/BEESOFT-3.14.0/Mac-BEESOFT-3.14.0-stable.pkg

**Comment by michaelDomingues** [comment]
It seems to be working.
Please update the stable release on BEEVERYCREATIVE's site (it is still hanged on 3.12.x)
